/*
 * OKCancelForm.java
 *
 * Copyright (C) 2009 Olivier Sechet
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package net.druppi.swing;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JRootPane;
import javax.swing.JSeparator;
import javax.swing.SwingConstants;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.event.AncestorEvent;
import javax.swing.event.AncestorListener;

import net.druppi.util.ResourceManager;


/**
 *
 * @author Olivier Sechet
 * @version 1.0 - Apr 13, 2009
 */
@SuppressWarnings("serial")
public class OKCancelForm extends javax.swing.JPanel {

    private final ActionListener okHandler;
    private final ActionListener applyHandler;
    private final ActionListener cancelHandler;

    /**
     * Creates new form OKCancelForm.
     */
    public OKCancelForm() {
        this(null, null, null);
    }

    /**
     * Creates new form OKCancelForm.
     */
    public OKCancelForm(final ActionListener okHandler, final ActionListener applyHandler,
            final ActionListener cancelHandler) {
        this.okHandler = okHandler;
        this.applyHandler = applyHandler;
        this.cancelHandler = cancelHandler;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        separator = new JSeparator();
        okButton = new JButton();
        applyButton = new JButton();
        cancelButton = new JButton();

        setName("Form"); // NOI18N
        addAncestorListener(new AncestorListener() {
            public void ancestorMoved(AncestorEvent evt) {
                formAncestorChanged(evt);
            }
            public void ancestorAdded(AncestorEvent evt) {
                formAncestorChanged(evt);
            }
            public void ancestorRemoved(AncestorEvent evt) {
                formAncestorChanged(evt);
            }
        });

        separator.setName("separator"); // NOI18N

        okButton.setText(ResourceManager.getResourceMap(getClass()).getString("OKCancelForm.okButton.text")); // NOI18N
        okButton.setName("okButton"); // NOI18N
        okButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        applyButton.setText(ResourceManager.getResourceMap(getClass()).getString("OKCancelForm.applyButton.text")); // NOI18N
        applyButton.setName("applyButton"); // NOI18N
        applyButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                applyButtonActionPerformed(evt);
            }
        });

        cancelButton.setText(ResourceManager.getResourceMap(getClass()).getString("OKCancelForm.cancelButton.text")); // NOI18N
        cancelButton.setName("cancelButton"); // NOI18N
        cancelButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(177, Short.MAX_VALUE)
                .addComponent(okButton)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(applyButton)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(cancelButton)
                .addContainerGap())
            .addComponent(separator, GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        layout.linkSize(SwingConstants.HORIZONTAL, new Component[] {applyButton, cancelButton, okButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(separator, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(Alignment.BASELINE, false)
                    .addComponent(applyButton)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(SwingConstants.VERTICAL, new Component[] {applyButton, cancelButton, okButton});

    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        if (okHandler != null) {
            okHandler.actionPerformed(evt);
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private void applyButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
        if (applyHandler != null) {
            applyHandler.actionPerformed(evt);
        }
    }//GEN-LAST:event_applyButtonActionPerformed

    private void cancelButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        if (cancelHandler != null) {
            cancelHandler.actionPerformed(evt);
        }
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * Called when the panel is added to a new ancestor.
     *
     * @param evt an event.
     */
    private void formAncestorChanged(AncestorEvent evt) {//GEN-FIRST:event_formAncestorChanged
        // Define the OK button as the default button of the rootPane.
        JRootPane rootPane = getRootPane();
        if (rootPane != null) {
            rootPane.setDefaultButton(okButton);
        }
    }//GEN-LAST:event_formAncestorChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    /** The apply button. */
    private JButton applyButton;
    /** The cancel button. */
    private JButton cancelButton;
    /** The OK button. */
    private JButton okButton;
    private JSeparator separator;
    // End of variables declaration//GEN-END:variables

}
